### ISSUE TITLE
Image not found on Dockerhub

### ISSUE THREAD

**Issue by strarsis** [bylexus/docker-apache-php53#1]
When I try to run (pull) the image, it cannot be found:

```
ERROR: Error: image bylexus/apache-php not found
```

Related (see Comments on the page): https://hub.docker.com/r/adamjimenez/apache-php/

**Comment by bylexus** [comment]
It seems that this is a documentation issue only: Instead of 
`docker run -d -P bylexus/apache-php`

it should be

`docker run -d -P bylexus/apache-php53`

I will update the docs accordingly.

**Comment by bylexus** [comment]
Documentation fix in 397e79a858969ef92a802850d5cac4e964df3cec
