### ISSUE TITLE
Can't get the container to load host files while using Kitematic

### ISSUE THREAD

**Issue by godbout** [bylexus/docker-apache-php53#3]
Hi there. I might be missing something very obvious, but I'm not able to see what's going on.

I create a new container through Kitematic with your image, and I put my files in the shared volume, but the container can't see the files. I terminaled into the container, and /var/www is empty. I also cannot create any file from within the container. It's saying that "the folder" doesn't exist.

Anything super obvious I'm missing? Thanks!

**Comment by bylexus** [comment]
Hi there,
I don't know kinematic, but with docker you would create your container with something like this:

`$ docker run -d -v /home/user/webroot:/var/www bylexus/apache-php53`

while /home/user/webroot would be your local webroot, and /var/www the container location. This works fine when created through docker. Maybe you have to configure this somewhere within Kinematic?

**Comment by godbout** [comment]
Thanks for the answer @bylexus. I thought you were the one who voluntarily put the package on the Kitematic repository, but I guess it's then just taken from the Docker Hub repository. Probably some changes have to be made in the Dockerfile to make it work directly through the Kitematic GUI rather than the command line (need an extra -v before the volumes :p). I'll check this out. Thanks!

**Comment by bylexus** [comment]
Thanks, if you have some inputs for Kinematic, I would adapt the Dockerfile if possible.

**Comment by godbout** [comment]
I'm gonna play a bit with that and let you know. Maybe at the end I might need to make my own image, not sure. Keep in touch.

**Comment by bylexus** [comment]
Hi,

Just tried my image with Kinematics, which worked out of the box with no problems. You have to choose the volume in the "Volumes" settings tab, otherwise it points to some default location, see screenshot:

![2016-07-18-dcetu](https://cloud.githubusercontent.com/assets/1824718/16920156/d92487d4-4d0c-11e6-9e05-d6669ec1c458.png)

Maybe this is useful for you,
alex

**Comment by godbout** [comment]
Hey Alex, thanks for checking. Yeah, I was configuring volumes. Actually I cloned your repository, build the image, and it worked out of the box. I haven't touched the Dockerfile. But when I download from Kitematic, it still doesn't work. Weird.
