### ISSUE TITLE
Can't be found on docker hub

### ISSUE THREAD

**Issue by vadimshvetsov** [bylexus/docker-apache-php53#5]
Hi.

There is not repo on docker hub, is it possible to publish it back?
https://hub.docker.com/r/bylexus/apache-php53

My image won't build because can't pull this base image :(

**Comment by bylexus** [comment]
Hi,
I will no longer maintain and deploy the image, as I am no longer using PHP 5.x, sorry. But feel free to pull this git and build an image by yourself. I will let the code in this repo as-is.

Sorry,
alex
